a:3:{s:5:"child";a:1:{s:0:"";a:1:{s:3:"rss";a:1:{i:0;a:6:{s:4:"data";s:0:"";s:7:"attribs";a:2:{s:0:"";a:1:{s:7:"version";s:4:"0.92";}s:36:"http://www.w3.org/XML/1998/namespace";a:1:{s:4:"base";s:21:"http://www.povnet.org";}}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";s:5:"child";a:1:{s:0:"";a:1:{s:7:"channel";a:1:{i:0;a:6:{s:4:"data";s:39:"
 
 
 
 






























";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";s:5:"child";a:1:{s:0:"";a:5:{s:5:"title";a:1:{i:0;a:5:{s:4:"data";s:71:"Aboriginal/First Nations News Feed | PovNet - Building Online Community";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}s:4:"link";a:1:{i:0;a:5:{s:4:"data";s:21:"http://www.povnet.org";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}s:11:"description";a:1:{i:0;a:5:{s:4:"data";s:375:"The following articles are fed through PovNet from outside mainstream and independent news sites, advocacy organizations, non-profits and government sites with the keywords first nations, aboriginal, native people, metis, Inuit, indigenous, aboriginal people in poverty, aboriginal poverty. These stories are not moderated and do not necessarily reflect the views of PovNet.
";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}s:8:"language";a:1:{i:0;a:5:{s:4:"data";s:2:"en";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}s:4:"item";a:30:{i:0;a:6:{s:4:"data";s:9:"
 
 
 
 
";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";s:5:"child";a:1:{s:0:"";a:4:{s:5:"title";a:1:{i:0;a:5:{s:4:"data";s:158:"Speaking Notes for the Honourable Chuck Strahl at a ceremony celebrating the signing of the Muskoday First Nation Treaty Land Entitlement Settlement Agreement";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}s:4:"link";a:1:{i:0;a:5:{s:4:"data";s:62:"http://www.nationtalk.ca/modules/news/article.php?storyid=6389";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}s:11:"description";a:1:{i:0;a:5:{s:4:"data";s:885:"Speaking Notes for the Honourable Chuck Strahl, PC, MP Minister of Indian Affairs and Northern Development and Federal Interlocutor for Métis and Non-Status Indians<br />at a ceremony celebrating the signing of the Muskoday First Nation Treaty Land Entitlement Settlement Agreement Muskoday First Nation<br />Saskatchewan<br />January 10, 2008<br /><br />Check against delivery<br /><br />Thank you. This is a truly historic day for your community, and Im honoured to share it with you. <br /><br />I want to begin by congratulating everyone from the Muskoday First Nation on this important achievement. Successfully negotiating a settlement is a true community effort -- it takes patience, open communication and decisive action. Together, you maintained consistent progress, negotiated in a spirit of goodwill and ratified the final agreement with clear support from your members.";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}s:7:"pubDate";a:1:{i:0;a:5:{s:4:"data";s:31:"Fri, 11 Jan 2008 12:02:34 -0800";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}}}}i:1;a:6:{s:4:"data";s:9:"
 
 
 
 
";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";s:5:"child";a:1:{s:0:"";a:4:{s:5:"title";a:1:{i:0;a:5:{s:4:"data";s:88:"AFN National Chief Congratulates Ontario First Nations on Historic Public Health Project";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}s:4:"link";a:1:{i:0;a:5:{s:4:"data";s:62:"http://www.nationtalk.ca/modules/news/article.php?storyid=6388";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}s:11:"description";a:1:{i:0;a:5:{s:4:"data";s:222:"OTTAWA, Jan. 11 - Today, AFN National Chief Phil Fontaine congratulated First Nations in Ontario for achieving a unique deal that will improve the delivery of public health services to First Nations communities in Ontario.";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}s:7:"pubDate";a:1:{i:0;a:5:{s:4:"data";s:31:"Fri, 11 Jan 2008 11:54:09 -0800";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}}}}i:2;a:6:{s:4:"data";s:9:"
 
 
 
 
";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";s:5:"child";a:1:{s:0:"";a:4:{s:5:"title";a:1:{i:0;a:5:{s:4:"data";s:230:"National Chief Phil Fontaine of the Assembly of First Nations expresses disappointment with the exclusion of Canada&#039;s First Nations people from today&#039;s upcoming First Ministers Meeting and issued the following Statement:";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}s:4:"link";a:1:{i:0;a:5:{s:4:"data";s:62:"http://www.nationtalk.ca/modules/news/article.php?storyid=6387";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}s:11:"description";a:1:{i:0;a:5:{s:4:"data";s:642:"OTTAWA, Jan. 11 - "The Prime Minister is hosting a First Ministers meeting today and has excluded First Nations participation in the discussions. With the economy as a key topic of discussion, the Prime and the Premiers should have included the Assembly of First Nations. We speak for the fastest growing demographic, with the youngest population in the country and our participation is key to the future economic success of Canada. First Nations people can be Canada's skilled workforce, but we first have to have access to the same quality of education, housing and living standards in our communities that the rest of Canada has in theirs.";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}s:7:"pubDate";a:1:{i:0;a:5:{s:4:"data";s:31:"Fri, 11 Jan 2008 11:50:19 -0800";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}}}}i:3;a:6:{s:4:"data";s:9:"
 
 
 
 
";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";s:5:"child";a:1:{s:0:"";a:4:{s:5:"title";a:1:{i:0;a:5:{s:4:"data";s:43:"Opportunity on Horizon for Canadian Sealers";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}s:4:"link";a:1:{i:0;a:5:{s:4:"data";s:62:"http://www.nationtalk.ca/modules/news/article.php?storyid=6386";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}s:11:"description";a:1:{i:0;a:5:{s:4:"data";s:411:"ST. JOHN'S, Jan. 9 - During a meeting yesterday in St. John's, NL, the Fur Institute of Canada's (FIC), Seals and Sealing Network assembled about 100 stakeholders from all aspects of sealing, sealers, Inuit, veterinarians, industry and government, to discuss the potential crisis in Europe based on pending seal product import bans, and the opportunity to meet and exceed European wildlife harvesting practices.";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}s:7:"pubDate";a:1:{i:0;a:5:{s:4:"data";s:31:"Fri, 11 Jan 2008 11:46:52 -0800";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}}}}i:4;a:6:{s:4:"data";s:9:"
 
 
 
 
";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";s:5:"child";a:1:{s:0:"";a:4:{s:5:"title";a:1:{i:0;a:5:{s:4:"data";s:93:"Horizon North Logistics Inc. Announces Completion of Acquisition of Pioneer Site Service Ltd.";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}s:4:"link";a:1:{i:0;a:5:{s:4:"data";s:62:"http://www.nationtalk.ca/modules/news/article.php?storyid=6385";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}s:11:"description";a:1:{i:0;a:5:{s:4:"data";s:747:"CALGARY, Jan. 10 - Horizon North Logistics Inc. ("Horizon" or the "Company") announces today that it has completed the acquisition of all of the common shares of Pioneer Site Services Ltd. ("Pioneer"). Pioneer owns a 49% interest in, and is the managing partner of two companies which provide camp catering services in Nunavut. The other 51% of the catering companies, Kitikmeot Caterers Ltd. and Sakku Caterers Ltd., is aboriginally owned by Kitikmeot Corporation and Sakku Investments Corp., respectively. Their mandate is to foster business and employment opportunities for the benefit of the Inuit people in their regions within Nunavut. The two catering companies are expected to generate combined revenue of approximately $5 million in 2008.";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}s:7:"pubDate";a:1:{i:0;a:5:{s:4:"data";s:31:"Fri, 11 Jan 2008 11:31:45 -0800";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}}}}i:5;a:6:{s:4:"data";s:9:"
 
 
 
 
";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";s:5:"child";a:1:{s:0:"";a:4:{s:5:"title";a:1:{i:0;a:5:{s:4:"data";s:13:"Hollowing-Out";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}s:4:"link";a:1:{i:0;a:5:{s:4:"data";s:54:"http://canadiandimension.com/articles/2008/01/11/1526/";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}s:11:"description";a:1:{i:0;a:5:{s:4:"data";s:778:"<p><em>Canadian Dimension magazine, January/February 2008</em></p>

<p>To live under external ownership and control has been the common fate of Canadians, and has powerfully conditioned our lives and our politics. Aboriginal people were so treated from early on by the settlers who, in turn, embraced their own lot as imperial subjects. As formal sovereignty shifted over time to the margin of empire, the tendency nevertheless was to welcome foreign capital to Canada, even to proclaim loudly that Canada was “open for business.” The rising American corporation of the late nineteenth century spilled over the border into Canada to the applause of Canadians. <a href="http://canadiandimension.com/articles/2008/01/11/1526/#more-1526" class="more-link">(more&#8230;)</a></p>";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}s:7:"pubDate";a:1:{i:0;a:5:{s:4:"data";s:31:"Fri, 11 Jan 2008 11:28:43 -0800";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}}}}i:6;a:6:{s:4:"data";s:9:"
 
 
 
 
";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";s:5:"child";a:1:{s:0:"";a:4:{s:5:"title";a:1:{i:0;a:5:{s:4:"data";s:70:"Inspiring Kick Off to 08 for Disabilities, Aboriginal Working Groups";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}s:4:"link";a:1:{i:0;a:5:{s:4:"data";s:62:"http://www.nationtalk.ca/modules/news/article.php?storyid=6384";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}s:11:"description";a:1:{i:0;a:5:{s:4:"data";s:243:"January 10, 2008 01:32 PM <br /><br />BURNABYCUPE BCs persons with disabilities working group and aboriginal working group got 2008 off to a productive start with inspiring guest speeches at their respective first meetings of the new year.";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}s:7:"pubDate";a:1:{i:0;a:5:{s:4:"data";s:31:"Fri, 11 Jan 2008 10:46:39 -0800";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}}}}i:7;a:6:{s:4:"data";s:9:"
 
 
 
 
";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";s:5:"child";a:1:{s:0:"";a:4:{s:5:"title";a:1:{i:0;a:5:{s:4:"data";s:43:"ACC - Winnipeg Convention Centre Open House";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}s:4:"link";a:1:{i:0;a:5:{s:4:"data";s:62:"http://www.nationtalk.ca/modules/news/article.php?storyid=6379";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}s:11:"description";a:1:{i:0;a:5:{s:4:"data";s:482:"Come join us for a wine & cheese after work business mixer.<br /><br />Hosted By:<br /><br />Winnipeg Convention Centre<br /><br />Date: January 31, 2008<br /><br />Time: 4:00 pm - 6:00 pm<br /><br />Location: 375 York Avenue<br /><br />Come see the latest renovations of our 2nd floor Concourse and learn more about some of our upcoming events.<br /><br />>><a href="http://aboriginalchamber.ca/wcm-docs/docs/attach-Open_House_january_31_2008_WCC.pdf" target="_blank">more info</a>";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}s:7:"pubDate";a:1:{i:0;a:5:{s:4:"data";s:31:"Fri, 11 Jan 2008 09:55:41 -0800";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}}}}i:8;a:6:{s:4:"data";s:9:"
 
 
 
 
";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";s:5:"child";a:1:{s:0:"";a:4:{s:5:"title";a:1:{i:0;a:5:{s:4:"data";s:60:"Expert mechanism adds implementation clout to UN declaration";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}s:4:"link";a:1:{i:0;a:5:{s:4:"data";s:54:"http://www.indiancountry.com/content.cfm?id=1096416412";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}s:11:"description";a:1:{i:0;a:5:{s:4:"data";s:205:"GENEVA - The adoption of the Declaration on the Rights of Indigenous Peoples by the U.N. General Assembly last September was hailed as a historic political and moral victory for the world;s 370 million ind";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}s:7:"pubDate";a:1:{i:0;a:5:{s:4:"data";s:31:"Fri, 11 Jan 2008 07:47:10 -0800";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}}}}i:9;a:6:{s:4:"data";s:9:"
 
 
 
 
";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";s:5:"child";a:1:{s:0:"";a:4:{s:5:"title";a:1:{i:0;a:5:{s:4:"data";s:30:"Laibar Singh Safe in Sanctuary";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}s:4:"link";a:1:{i:0;a:5:{s:4:"data";s:50:"http://mostlywater.org/laibar_singh_safe_sanctuary";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}s:11:"description";a:1:{i:0;a:5:{s:4:"data";s:13249:"<p>Laibar Singh Safe in Sanctuary</p>

<p>(important ways to support and UPCOMING EVENTS/ACTIONS, including cross-country are included below)</p>
<p><img src="http://noii-van.resist.ca/wp-content/uploads/2008/01/2181140376_6bd3b50d63.jpg" alt="2181140376_6bd3b50d63.jpg" style="width: 280px; height: 209px;" align="left" height="209" width="280">As people have likely heard by now, Mr. Laibar Singh was not deported on yesterday December 9th at 4:30 am and remains in sanctuary in Guru Nanak Sikh Temple in Surrey. The last minute notice of the deportation and the removal time of 4:30 am was a deliberate and under-handed attempt to thwart public outcry and support. At 4:00 am, approximately 300 supporters gathered to protest and bear witness to CBSA’s enforcement of a deportation in violation of sanctuary. In light of a major backlash for violating sanctuary and in the presence of hundreds of supporters, CBSA<br>
backed off from the deportation.</p>

<p><img src="http://noii-van.resist.ca/wp-content/uploads/2008/01/2181094434_6ef903eea2.jpg" alt="2181094434_6ef903eea2.jpg" style="width: 200px; height: 150px;" align="left" height="150" width="200">The Surrey Guru Nanak Gurudwara has made clear to CBSA that Laibar Singh is in sanctuary in their premises. In having decided to enter temple premises yesterday or any date in the future, CBSA is breaching a historic moral tradition of sanctuary. Sanctuary is an act of courage that faith communities take to protect the lives of those facing deportation in light of unjust government decisions.</p>
<p><a id="more-613"></a></p>
<p>In a December 20, 2007 press release the Ontario Sanctuary Coalition stated “We reaffirm the regrettable necessity of the practice of granting Sanctuary… [Sanctuary] has now become a national movement of conscience.” Denise Nadeau of the Interfaith Sanctuary Coalition and Acting Director of the SFU Interfaith Summer Institute states “The deportation of Laibar Singh from sanctuary and in the face of massive public support for this man’s right to dignity and to live with his<br>
community is a fragrant violation not only of sanctuary but of the basic human rights of disabled persons, of asylum seekers and of the democratic will of a significant proportion of the population.”</p>
<p>In fact, a May 2007 report by the House of Commons Standing Committee on Citizenship and Immigration whose members include MP’s Norman Doyle, Andrew Telegdi, Meili Faille, Omar Alghabra, Dave Batters, Barry Devolin, Raymond Gravel, Nina Grewal, Jim Karygiannis, Ed Komarnicki, Bill Siksay, and Blair Wilson, recommended the following to CBSA and CIC “That CIC, the CBSA, and law enforcement officials respect the right of churches and other religious organizations to provide sanctuary to those they believe are in need of protection… That in cases of MEDICAL EMERGENCIES (emphasis added), those who have sought sanctuary, and members of their family, be allowed to receive medical treatment without the threat that they will be arrested or detained.” The August 2007 decision by CBSA to<br>
detain Mr. Laibar Singh while he was receiving emergency care and any future attempts by CBSA to detain Mr. Laibar Singh if he requires medical emergency care would clearly be in defiance and contravention of the government’s own recommendations.</p>
<p>Recent sensationalist media reports have attempted to question the significance of Mr. Laibar Singh’s medical condition. There is clearly no doubt that Mr. Singh is a severely disabled and paralyzed man. Immigration Canada’s own health assessments recognize the severity of Mr. Singh’s condition. Various doctors have dealt with Mr. Singh and have stated various causes of his paralysis; yet the basic issue remains the same: Mr. Singh is a severely disabled and paralyzed man who should be able to remain in Canada on humanitarian and compassionate grounds.</p>
<p>As expected unfortunately, there has been a significant backlash yet again to the South Asian community and to refugee struggles in general. Pete McMartin at the Vancouver Sun (who previously had written about a $5 bet with his editor about the outcome of the case) has quoted Don DeVoretz, an advisor to the CBSA, as stating how past legal Charter victories which now afford some (minimal) protection to refugees have “bogged down the immigration process” and how it is negative and undesirable that with time a refugee is able to “to integrate oneself into the community.” The significant media scrutiny and questioning of this case and the South Asian community at-large has revealed the ways in which<br>
immigrant/racialized communities as awhole who are constantly reminded of their subordinate position especially during moments of resistance to the Canadian state.</p>

<p>Finally, a <strong>growing list of supporters</strong> are demanding that Mr. Laibar Singh be granted permanent residency on humanitarian and compassionate grounds. These supporters include Michael A. Leitold of the Law Union of Ontario<br>
Steering Committee, Janet Cleveland who holds the Canada Research Chair in International Migration Law, noted authors and researchers Naomi Klein and Seth Klein, Professor and Japanese-Canadian redress activist Roy Mikki (Order of Canada), Kader Belaouni who has been in sanctuary in Montreal since Jan 2006, Sister Elizabeth Kelliher of the Fransican Sister of the Atonement, labour activists such as Dave Bleakney of CUPW and Frank Lee of CUPE, academics such as John Price, Nandita Sharma, Cynthia Wright, Gary Kinsman, and Maro Jo Nadeau, Rabble Editor Derrick O’Keefe, along with the Canadian Labour Congress, Hospital Employees Union, BC Coalition of People with Disabilities, Canadian Union of Postal Workers, Council of Canadians BC/Yukon Chapter, Save our Rivers Society, Multifaith Action Committee,<br>
Association of Chinese Canadians for Equality and Solidarity Society, Indigenous Free Skool, Solidarity Across Borders Montreal, No One Is Illegal Toronto, Industrial Workers of the World, Vancouver Status of Women, La Surda Latin American Collective, Interfaith Community Consultative Committee of the SFU Interfaith Summer Institute, Ligue des droits et libertés du Québec, Student Christian Movement of Canada, Students for a Democratic Society UBC, Halifax Coalition Against Poverty, Vancouver Catholic Worker, Immigrant Workers Centre Montreal, Canadian Youth Network for Asia Pacific Solidarity, and countless more individuals and community groups.</p>
<p>It is also important to note that Mr. Singh’s case is not unprecedented. In October 2006, a Polish family on tourist visas in Winnipeg suffered from a car accident that left the father paralyzed. Initially they were refused; however their deportation order was subsequently overturned. Ministerial discretion in humanitarian and compassionate claims can and has been exercised in the past to stop deportations; <em>in fact it exists for that very purpose</em>.</p>
<p>We believe it is unfortunate that some are declaring that he must leave because he does not “belong” any longer, despite the fact that his newly found family and community are here. Certainly his physical state of paralysis and the widespread community support he has received are all crucial factors and realities for Mr. Singh. He, like anyone else, should<br>
be entitled to live a healthy and dignified life.</p>

<p>We must challenge the idea that some are more worthy than others to decide their right to mobility and their assertion of self determination; instead we should accept these as universal values of humanity. The struggle against deportation and to support Laibar is not for him alone nor is it simply one case, rather it symbolizes the struggles for all immigrant and<br>
refugees who daily struggle to live with dignity. His situation reveals how hard and long racialized migrants must fight to assert their right to self-determination that the Canadian government consistently denies and instead perpetuates pain, anxiety, and violence through detentions and deportations against which we must continue to actively organize<br>
ourselves.</p>
<p>All Power to the People! No One is Illegal!<br>
For more information call 778 552 2099 or email noii-van@resist.ca For an excellent backgrounder visit Communities For Laibar Singh: http://supportlaibar.blogspot.com/</p>
<p>==&gt; WAYS TO SUPPORT AND UPCOMING EVENTS/ACTIONS &lt;==</p>
<p>1) Please attend the <strong>community forum</strong> in support of Laibar Singh and on broader issues of migration and race with speakers lawyer Zool Suleman, representatives of the Canadian Labour Congress and Hospital Employees Union, theologian Denise Nadeau, and South Asian community organizers Gurpreet Singh and Gurvinder Dhaliwal.</p>

<p>Details: Saturday Jan 12th at 5:45 pm at Vancouver Public Library.<br>
Organized by Communities for Laibar Singh. Call 604 779 7430.<br>
Further details are available at: http://noii-van.resist.ca/?p=610</p>
<p>2) Please write letters to the editor, post online, or call into radio shows into the <strong>various media outlets</strong> that are covering this story. We strongly urge and stress to supporters the importance of voicing your opinion on this issue and adding your thoughts to the very public debate on Laibar Singh and immigration in general. Although it may seem futile and given the biases that have been clearly stated by various media outlets, it is still absolutely crucial for us to enter this public debate and discourse at this time.</p>
<p>3) Please stay in tune for details on an upcoming vigil in support of Laibar Singh as part of a <strong>National Day of Action</strong> in Support of Laibar Singh along with allies in Montreal, Toronto and other cities.</p>
<p>*** Our allies in Toronto with No One Is Illegal Toronto, Sikh Activist Network and their supporters are organizing a delegation and press conference in support of Laibar Singh. Details: FRIDAY JAN 11 at 10am at 25 St. Clair Avenue East, Toronto (Immigration Canada Regional offices. Please visit toronto.nooneisillegal.org for more details.</p>

<p>4) Please continue to <strong>pressure Immigration Minister Diane Finley</strong>. We realize that most of you are probably flooded by letter-writing campaigns or find letter-writing futile. However, it is CLEAR that the government has been forced to respond to an unparalled amount of support and pressure and it is time that they get the message and grant Mr. Laibar Singh a permanent stay on his deportation order. If you have called or written before, please do so again!</p>
<p>IMMIGRATION MINISTER DIANE FINLAY<br>
* CALL (PREFERABLE): (613) 996-4974<br>
* FAX: (613) 996-9749<br>
* EMAIL: minister at cic.gc.ca and Finley.D at parl.gc.ca</p>
<p>MINISTER STOCKWELL DAY (RESPONSIBLE FOR CBSA)<br>
* CALL: 613.995.1702 or 250.770.4480<br>
* FAX: 613.995.1154 or 250.770.4484<br>

* EMAIL: day.s at parl.gc.ca or days1 at parl.gc.ca</p>
<p>======&gt; SAMPLE LETTER &lt;========</p>
<p>Minister Finley and Minister Day,</p>
<p>Regarding: Laibar Singh</p>
<p>I am writing regarding the situation of Mr. Laiber Singh. I am sure that you are aware of the case of the paralyzed Punjabi refugee claimant Mr. Laiber Singh, who is currently facing deportation .&nbsp; A wide variety of human rights organizations, disability advocates and community groups have also expressed their support for Mr. Singh’s bid to remain in Canada on humanitarian and compassionate grounds. These groups include the Canadian Labour Congress, BC Coalition of People with Disabilities, B.C Hospital Employees Union, the Multifaith&nbsp; Action Committee, and a long list of South Asian community groups and gurudwaras.</p>

<p>Over the past few months, approximately forty thousand people have signed an Official petition to Parlimament in support of Mr. Singh remaining in Canada on humanitarian and compassionate grounds.</p>
<p>On October 9, 2007, a group of health care professionals- including 13 independent doctors- issued a letter to Immigration Minster Diane Finley stating, “As health professionals, we are outraged at the fact that the Canadian government would consider deporting a paraplegic man, whose health condition is extremely fragile… For the sake of his safety, health and well being, we fully support him and demand that [the Minister] grant him permanent residency status on the basis of humanitarian and compassionate grounds immediately.”</p>
<p>It is outrageous that the Canadian government would deport a man who is already struggling to life a live of dignity and autonomy, and whose physical health is so fragile.For the sake of his own safety, for the well-being of his physical health, and based on the life that Mr.Singh has already established, I fully support him and demand that you stop the deportation of Mr. Laibar Singh immediately and grant him permanent residency status. I also urgently request that the Canadian government and CBSA officals respect the sanctity of sanctuary that the Guru Nanak Sikh temple have granted to Mr. Laibar Singh and not attempt to remove Mr. Singh from sanctuary or detain him if he requires urgent medical attention<br>
at a medical facility.</p>";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}s:7:"pubDate";a:1:{i:0;a:5:{s:4:"data";s:31:"Thu, 10 Jan 2008 19:30:16 -0800";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}}}}i:10;a:6:{s:4:"data";s:9:"
 
 
 
 
";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";s:5:"child";a:1:{s:0:"";a:4:{s:5:"title";a:1:{i:0;a:5:{s:4:"data";s:55:"Gwich'in companies will get more work, minister pledges";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}s:4:"link";a:1:{i:0;a:5:{s:4:"data";s:73:"http://www.cbc.ca/canada/north/story/2008/01/10/gwichin-work.html?ref=rss";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}s:11:"description";a:1:{i:0;a:5:{s:4:"data";s:162:"The Northwest Territories government has promised to give more work to Gwich'in aboriginal businesses, addressing complaints raised by a Gwich'in chief this week.";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}s:7:"pubDate";a:1:{i:0;a:5:{s:4:"data";s:31:"Thu, 10 Jan 2008 15:42:09 -0800";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}}}}i:11;a:6:{s:4:"data";s:9:"
 
 
 
 
";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";s:5:"child";a:1:{s:0:"";a:4:{s:5:"title";a:1:{i:0;a:5:{s:4:"data";s:94:"CANADA CELEBRATES SETTLEMENT AGREEMENT WITH MUSKODAY FIRST NATION AND PROVINCE OF SASKATCHEWAN";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}s:4:"link";a:1:{i:0;a:5:{s:4:"data";s:69:"http://www.gov.sk.ca/news?newsId=3e92407c-6b8c-487b-9a2d-74fb4dfc7d27";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}s:11:"description";a:1:{i:0;a:5:{s:4:"data";s:384:"<p>Chuck Strahl, Minister of Indian Affairs and Northern Development and Federal Interlocutor for M&eacute;tis and Non-Status Indians, today participated in a ceremony celebrating the signing of a Treaty Land Entitlement (TLE) Settlement Agreement with Chief Austin Bear of the Muskoday First Nation, and Saskatchewan First Nations and M&eacute;tis Relations Minister June Draude.</p>";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}s:7:"pubDate";a:1:{i:0;a:5:{s:4:"data";s:31:"Thu, 10 Jan 2008 13:00:00 -0800";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}}}}i:12;a:6:{s:4:"data";s:9:"
 
 
 
 
";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";s:5:"child";a:1:{s:0:"";a:4:{s:5:"title";a:1:{i:0;a:5:{s:4:"data";s:80:"Government of Canada Funds Groundbreaking First Nations Public Health Initiative";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}s:4:"link";a:1:{i:0;a:5:{s:4:"data";s:63:"http://www.news.gc.ca:80/web/view/en/index.jsp?articleid=371499";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}s:11:"description";a:1:{i:0;a:5:{s:4:"data";s:345:"<![CDATA[The Honourable Tony Clement, Minister of Health and Minister for the Federal Economic Development Initiative for Northern Ontario, today announced that the Government of Canada is investing $3.7 million to ensure that public health services can be more efficient and effectively delivered in First Nations communities across Ontario.]]>";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}s:7:"pubDate";a:1:{i:0;a:5:{s:4:"data";s:31:"Thu, 10 Jan 2008 11:35:00 -0800";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}}}}i:13;a:6:{s:4:"data";s:9:"
 
 
 
 
";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";s:5:"child";a:1:{s:0:"";a:4:{s:5:"title";a:1:{i:0;a:5:{s:4:"data";s:94:"Canada Celebrates Settlement Agreement With Muskoday First Nation And Province Of Saskatchewan";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}s:4:"link";a:1:{i:0;a:5:{s:4:"data";s:63:"http://www.news.gc.ca:80/web/view/en/index.jsp?articleid=371519";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}s:11:"description";a:1:{i:0;a:5:{s:4:"data";s:535:"<![CDATA[Muskoday First Nation, SK (January 10, 2008) - The Honourable Chuck Strahl, Minister of Indian Affairs and Northern Development and Federal Interlocutor for Métis and Non-Status Indians, today participated in a ceremony celebrating the signing of a Treaty Land Entitlement (external link, opens a new window) (TLE)    Settlement Agreement with Chief Austin Bear of the Muskoday First Nation (external link, opens a new window),   and the Honourable June Draude, Saskatchewan Minister of First Nations and Métis Relations.]]>";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}s:7:"pubDate";a:1:{i:0;a:5:{s:4:"data";s:31:"Thu, 10 Jan 2008 10:10:00 -0800";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}}}}i:14;a:6:{s:4:"data";s:9:"
 
 
 
 
";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";s:5:"child";a:1:{s:0:"";a:4:{s:5:"title";a:1:{i:0;a:5:{s:4:"data";s:41:"MNS leader plans on reforms - StarPhoenix";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}s:4:"link";a:1:{i:0;a:5:{s:4:"data";s:62:"http://www.nationtalk.ca/modules/news/article.php?storyid=6350";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}s:11:"description";a:1:{i:0;a:5:{s:4:"data";s:556:"MNS leader plans on reforms<br /><br />Matthew Kruchak, The StarPhoenix<br />Published: Thursday, January 10, 2008<br /><br />The recently elected leader of Metis Nation-Saskatchewan (MNS) says he's working to create an organization that governments can trust, but more importantly, one its own people can confide in.<br /><br /><a href="http://www.canada.com/saskatoonstarphoenix/news/story.html?id=139d8693-0df9-42f6-9a64-8fa9e0630c91" target="_blank">http://www.canada.com/saskatoonstarphoenix/news/story.html?id=139d8693-0df9-42f6-9a64-8fa9e0630c91</a>";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}s:7:"pubDate";a:1:{i:0;a:5:{s:4:"data";s:31:"Thu, 10 Jan 2008 08:20:24 -0800";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}}}}i:15;a:6:{s:4:"data";s:9:"
 
 
 
 
";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";s:5:"child";a:1:{s:0:"";a:4:{s:5:"title";a:1:{i:0;a:5:{s:4:"data";s:60:"Conservation Groups Suing U.S. Over Polar Bear Listing - CBC";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}s:4:"link";a:1:{i:0;a:5:{s:4:"data";s:62:"http://www.nationtalk.ca/modules/news/article.php?storyid=6348";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}s:11:"description";a:1:{i:0;a:5:{s:4:"data";s:557:"Conservation groups suing U.S. over polar bear listing<br /><br />Last Updated: Thursday, January 10, 2008 | 10:37 AM CT <br />The Associated Press<br /> <br />Three conservation groups notified the U.S. government Wednesday they intend to sue to get polar bears listed as a threatened species due to global warming, in a case that could have a major effect on Inuit hunting guides in Canada.<br /><br /><a href="http://www.cbc.ca/canada/north/story/2008/01/10/ap-polar.html" target="_blank">http://www.cbc.ca/canada/north/story/2008/01/10/ap-polar.html</a>";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}s:7:"pubDate";a:1:{i:0;a:5:{s:4:"data";s:31:"Thu, 10 Jan 2008 08:17:59 -0800";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}}}}i:16;a:6:{s:4:"data";s:9:"
 
 
 
 
";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";s:5:"child";a:1:{s:0:"";a:4:{s:5:"title";a:1:{i:0;a:5:{s:4:"data";s:27:"Spirited away - Macleans.ca";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}s:4:"link";a:1:{i:0;a:5:{s:4:"data";s:62:"http://www.nationtalk.ca/modules/news/article.php?storyid=6347";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}s:11:"description";a:1:{i:0;a:5:{s:4:"data";s:1077:"Spirited away<br />The snatching of a B.C. teacher for a native ritual raises questions<br /><br />KEN MACQUEEN | January 9, 2008 | <br /><br />Roxanne Harris grew up on the Chemainus Indian reserve on the southeast coast of Vancouver Island, and she attended North Oyster elementary school in nearby Ladysmith. She was a good student with deep ties to her Coast Salish culture. Harris went on to university, received her teaching accreditation, and returned to teach at the school, where her job is to instill Aboriginal culture in students. On Dec. 14, she unwittingly gave the entire community a lesson in ancient Salish traditions  and their collision with modern notions of individual rights and personal security. A band delegation, including Harris's father, George Harris, snatched the protesting 32-year-old teacher from the school for a secretive longhouse ritual.<br /><br /><a href="http://www.macleans.ca/canada/national/article.jsp?content=20080109_43100_43100" target="_blank">http://www.macleans.ca/canada/national/article.jsp?content=20080109_43100_43100</a>";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}s:7:"pubDate";a:1:{i:0;a:5:{s:4:"data";s:31:"Thu, 10 Jan 2008 08:04:04 -0800";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}}}}i:17;a:6:{s:4:"data";s:9:"
 
 
 
 
";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";s:5:"child";a:1:{s:0:"";a:4:{s:5:"title";a:1:{i:0;a:5:{s:4:"data";s:105:"New Stats Good Step Forward in Portraying Canada&#039;s Complex Adult Literacy Landscape, says ABC CANADA";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}s:4:"link";a:1:{i:0;a:5:{s:4:"data";s:62:"http://www.nationtalk.ca/modules/news/article.php?storyid=6346";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}s:11:"description";a:1:{i:0;a:5:{s:4:"data";s:580:"FOR IMMEDIATE RELEASE<br /><br />TORONTO, ON  January 10, 2008  New findings about the reading ability of Canadian adults who are most greatly challenged by low literacy underscore the extent and the complex nature of our country's literacy dilemma. Released yesterday by Statistics Canada, Learning Literacy in Canada: Evidence from the International Survey of Reading Skills identifies a number of groups of people at risk  among them, seniors, immigrants, low-income Canadians and Aboriginal people  who face varying and distinct reading and comprehension difficulties.";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}s:7:"pubDate";a:1:{i:0;a:5:{s:4:"data";s:31:"Thu, 10 Jan 2008 08:01:59 -0800";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}}}}i:18;a:6:{s:4:"data";s:9:"
 
 
 
 
";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";s:5:"child";a:1:{s:0:"";a:4:{s:5:"title";a:1:{i:0;a:5:{s:4:"data";s:69:"Indigenous academic tells First Nations to take charge - McGill Daily";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}s:4:"link";a:1:{i:0;a:5:{s:4:"data";s:62:"http://www.nationtalk.ca/modules/news/article.php?storyid=6345";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}s:11:"description";a:1:{i:0;a:5:{s:4:"data";s:415:"Indigenous academic tells First Nations to take charge<br /><br />By Scott Pearl<br />News Writer<br /><br />Canadas indigenous community must strive toward self-empowerment, according to an indigenous scholar visiting Concordias School of Community and Public Affairs last night.<br /><br /><a href="http://www.mcgilldaily.com/view.php?aid=6833" target="_blank">http://www.mcgilldaily.com/view.php?aid=6833</a>";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}s:7:"pubDate";a:1:{i:0;a:5:{s:4:"data";s:31:"Thu, 10 Jan 2008 07:59:30 -0800";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}}}}i:19;a:6:{s:4:"data";s:9:"
 
 
 
 
";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";s:5:"child";a:1:{s:0:"";a:4:{s:5:"title";a:1:{i:0;a:5:{s:4:"data";s:71:"First Nations chief testifies hotel sex was consensual - The Daily News";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}s:4:"link";a:1:{i:0;a:5:{s:4:"data";s:62:"http://www.nationtalk.ca/modules/news/article.php?storyid=6343";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}s:11:"description";a:1:{i:0;a:5:{s:4:"data";s:434:"First Nations chief testifies hotel sex was consensual  <br /><br />RICHARD CUTHBERTSON <br />The Daily News<br />Last updated at 6:39 AM on 10/01/08   <br /><br />The chief of Chapel Island First Nation testified yesterday he had sex with a woman at a Dartmouth hotel, but said it was consensual.<br /><br /><a href="http://www.hfxnews.ca/index.cfm?sid=96550&sc=89" target="_blank">http://www.hfxnews.ca/index.cfm?sid=96550&sc=89</a>";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}s:7:"pubDate";a:1:{i:0;a:5:{s:4:"data";s:31:"Thu, 10 Jan 2008 07:54:59 -0800";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}}}}i:20;a:6:{s:4:"data";s:9:"
 
 
 
 
";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";s:5:"child";a:1:{s:0:"";a:4:{s:5:"title";a:1:{i:0;a:5:{s:4:"data";s:48:"Indigenous section OK;d by anthropological group";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}s:4:"link";a:1:{i:0;a:5:{s:4:"data";s:54:"http://www.indiancountry.com/content.cfm?id=1096416366";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}s:11:"description";a:1:{i:0;a:5:{s:4:"data";s:175:"WASHINGTON - The American Anthropological Association board of directors approved an indigenous section of its membership for the first time on Dec. 5. The vote was unanimous.";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}s:7:"pubDate";a:1:{i:0;a:5:{s:4:"data";s:31:"Thu, 10 Jan 2008 07:00:54 -0800";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}}}}i:21;a:6:{s:4:"data";s:9:"
 
 
 
 
";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";s:5:"child";a:1:{s:0:"";a:4:{s:5:"title";a:1:{i:0;a:5:{s:4:"data";s:79:"Ms. Wendy Johnson appointed to the position of Vice-President of Bell & Bernard";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}s:4:"link";a:1:{i:0;a:5:{s:4:"data";s:62:"http://www.nationtalk.ca/modules/news/article.php?storyid=6327";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}s:11:"description";a:1:{i:0;a:5:{s:4:"data";s:407:"FOR IMMEDIATE RELEASE            <br /><br />January 9, 2008 - Six Nations of the Grand River - Bell & Bernard Limited (BBL), Canadas preeminent consulting firm in the field of First Nations economic development is pleased to announce the appointment of Ms. Wendy Johnson to the position of Vice-President. Ms. Johnson is from Six Nations of the Grand River Territory and is a member of the Mohawk Nation.";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}s:7:"pubDate";a:1:{i:0;a:5:{s:4:"data";s:31:"Wed,  9 Jan 2008 14:25:38 -0800";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}}}}i:22;a:6:{s:4:"data";s:9:"
 
 
 
 
";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";s:5:"child";a:1:{s:0:"";a:4:{s:5:"title";a:1:{i:0;a:5:{s:4:"data";s:52:"Dehcho to Hold Special Assembly on Grand Chief Issue";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}s:4:"link";a:1:{i:0;a:5:{s:4:"data";s:62:"http://www.nationtalk.ca/modules/news/article.php?storyid=6323";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}s:11:"description";a:1:{i:0;a:5:{s:4:"data";s:220:"FOR IMMEDIATE RELEASE<br /><br />FORT SIMPSON, NT.  A Special Assembly of the Dehcho First Nations (DFN) will be held January 29-31, 2008, to discuss and review the question of Grand Chief Herb Norwegians leadership.";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}s:7:"pubDate";a:1:{i:0;a:5:{s:4:"data";s:31:"Wed,  9 Jan 2008 12:37:28 -0800";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}}}}i:23;a:6:{s:4:"data";s:9:"
 
 
 
 
";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";s:5:"child";a:1:{s:0:"";a:4:{s:5:"title";a:1:{i:0;a:5:{s:4:"data";s:36:"Media Advisory: Government of Canada";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}s:4:"link";a:1:{i:0;a:5:{s:4:"data";s:62:"http://www.nationtalk.ca/modules/news/article.php?storyid=6319";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}s:11:"description";a:1:{i:0;a:5:{s:4:"data";s:907:"OTTAWA, ONTARIO--(Jan. 9, 2008) - Media representatives are invited to attend a ceremony to celebrate an important milestone in the negotiation of the Muskoday First Nation specific claim concerning Treaty Land Entitlement.<br /><br />The Honourable Chuck Strahl, Minister of Indian Affairs and Northern Development and Federal Interlocutor for Metis and Non-Status Indians, Chief Austin Bear of the Muskoday First Nation and the Honourable June Draude, Minister of First Nations and Metis Relations, Province of Saskatchewan will be in attendance.<br /><br />When:Thursday, January 10, 2008 at 1 p.m.<br />Where:Muskoday School,Muskoday First Nation,Saskatchewan<br />  <br /><br />For more information, please contact<br /><br />Office of the Honourable Chuck Strahl<br />Ted Yeomans<br />819-997-0002<br /><br />or<br /><br />Indian and Northern Affairs Canada<br />Media Relations Line<br />819-953-1160";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}s:7:"pubDate";a:1:{i:0;a:5:{s:4:"data";s:31:"Wed,  9 Jan 2008 12:05:43 -0800";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}}}}i:24;a:6:{s:4:"data";s:9:"
 
 
 
 
";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";s:5:"child";a:1:{s:0:"";a:4:{s:5:"title";a:1:{i:0;a:5:{s:4:"data";s:46:"City 'stalls' on plan for jobs for aboriginals";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}s:4:"link";a:1:{i:0;a:5:{s:4:"data";s:67:"http://www.winnipegfreepress.com/local/story/4103891p-4702187c.html";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}s:11:"description";a:1:{i:0;a:5:{s:4:"data";s:408:"CITY Hall has hardly budged on a plan to give young aboriginal Winnipeggers a chance at jobs with the city, says the councillor who first tabled the proposal last year.  St. Boniface Coun. Dan Vandal is unhappy his call for an urban aboriginal youth job strategy -- a pitch seconded by Mayor Sam Katz -- has gone unheeded since Katz's cabinet decided to hand off the issue to a city department last February.";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}s:7:"pubDate";a:1:{i:0;a:5:{s:4:"data";s:31:"Wed,  9 Jan 2008 06:47:06 -0800";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}}}}i:25;a:6:{s:4:"data";s:9:"
 
 
 
 
";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";s:5:"child";a:1:{s:0:"";a:4:{s:5:"title";a:1:{i:0;a:5:{s:4:"data";s:49:"Manitoba group aims to find missing native people";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}s:4:"link";a:1:{i:0;a:5:{s:4:"data";s:82:"http://www.cbc.ca/canada/manitoba/story/2008/01/09/missing-aboriginal.html?ref=rss";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}s:11:"description";a:1:{i:0;a:5:{s:4:"data";s:84:"A new community group has formed in Winnipeg to help find missing aboriginal people.";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}s:7:"pubDate";a:1:{i:0;a:5:{s:4:"data";s:31:"Wed,  9 Jan 2008 06:30:09 -0800";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}}}}i:26;a:6:{s:4:"data";s:9:"
 
 
 
 
";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";s:5:"child";a:1:{s:0:"";a:4:{s:5:"title";a:1:{i:0;a:5:{s:4:"data";s:53:"Sex complaint linked to Nunatsiavut president's leave";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}s:4:"link";a:1:{i:0;a:5:{s:4:"data";s:91:"http://www.cbc.ca/canada/newfoundland-labrador/story/2008/01/09/andersen-leave.html?ref=rss";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}s:11:"description";a:1:{i:0;a:5:{s:4:"data";s:149:"The president of the Inuit self-government in Labrador has stepped aside partly because of a sexual assault investigation, the acting president says.";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}s:7:"pubDate";a:1:{i:0;a:5:{s:4:"data";s:31:"Wed,  9 Jan 2008 05:03:51 -0800";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}}}}i:27;a:6:{s:4:"data";s:9:"
 
 
 
 
";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";s:5:"child";a:1:{s:0:"";a:4:{s:5:"title";a:1:{i:0;a:5:{s:4:"data";s:53:"Sex complaint linked to Nunatsiavut president's leave";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}s:4:"link";a:1:{i:0;a:5:{s:4:"data";s:75:"http://www.cbc.ca/canada/north/story/2008/01/09/andersen-leave.html?ref=rss";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}s:11:"description";a:1:{i:0;a:5:{s:4:"data";s:149:"The president of the Inuit self-government in Labrador has stepped aside partly because of a sexual assault investigation, the acting president says.";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}s:7:"pubDate";a:1:{i:0;a:5:{s:4:"data";s:31:"Wed,  9 Jan 2008 05:03:51 -0800";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}}}}i:28;a:6:{s:4:"data";s:9:"
 
 
 
 
";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";s:5:"child";a:1:{s:0:"";a:4:{s:5:"title";a:1:{i:0;a:5:{s:4:"data";s:53:"Sex complaint linked to Nunatsiavut president's leave";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}s:4:"link";a:1:{i:0;a:5:{s:4:"data";s:91:"http://www.cbc.ca/canada/newfoundland-labrador/story/2008/01/09/andersen-leave.html?ref=rss";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}s:11:"description";a:1:{i:0;a:5:{s:4:"data";s:149:"The president of the Inuit self-government in Labrador has stepped aside partly because of a sexual assault investigation, the acting president says.";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}s:7:"pubDate";a:1:{i:0;a:5:{s:4:"data";s:31:"Wed,  9 Jan 2008 05:03:51 -0800";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}}}}i:29;a:6:{s:4:"data";s:9:"
 
 
 
 
";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";s:5:"child";a:1:{s:0:"";a:4:{s:5:"title";a:1:{i:0;a:5:{s:4:"data";s:56:"Out of the Algonquin Frying Pan and into the Mohawk Fire";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}s:4:"link";a:1:{i:0;a:5:{s:4:"data";s:44:"http://www.dominionpaper.ca/weblogs/dru/1609";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}s:11:"description";a:1:{i:0;a:5:{s:4:"data";s:1572:"[<em>The following is a letter to the editor received on Jan 8, 2008</em>]

From the beginning, the Crown, Ontario and agents wanted the farcical mediation meetings to be held behind closed doors. They wanted to isolate the Ardoch and Shabot Algonquin "leadership" to make secret $deals$ over a supposed uranium mine. According to Indigenous law, such meetings that concern the people should be open to the people as the Algonquins have repeatedly insisted.

Suddenly, Ontario says the meetings are open to the public but now they are to be held in Kingston, outside of Algonquin territory, two hours away from the affected community. Moving the mediation out of Algonquin territory is also a breach of Algonquin law.

However, this is a clear case of the proverbial, "Out of the frying pan and into the fire!" Kingston is in Mohawk territory!

Why, we must ask, would the meetings be moved to Kingston? For whose convenience? We hear rumours of Crown agents who need city night life and their accustomed type of "watering hole", not available in the remote areas of Sharbot Lake. The new location was certainly handy for the Mohawks, perhaps too handy. When they changed the venue, the mediation team knew Kahentinetha Horn of MNN was planning to attend - Randy Cota and Bob Lovelace had invited her!

(In July 2007, the Algonquins sent a wampum to the Mohawks seeking their help in the blockade against uranium mining at Robertsville. Nuclear development on Algonquin land would affect Mohawk communities downstream. This official nation to nation agreement is ongoing.)";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}s:7:"pubDate";a:1:{i:0;a:5:{s:4:"data";s:31:"Tue,  8 Jan 2008 23:10:23 -0800";s:7:"attribs";a:0:{}s:8:"xml_base";s:21:"http://www.povnet.org";s:17:"xml_base_explicit";b:1;s:8:"xml_lang";s:0:"";}}}}}}}}}}}}}}}}s:7:"headers";a:10:{s:4:"date";s:29:"Sat, 12 Jan 2008 14:45:03 GMT";s:6:"server";s:22:"Apache/2.0.52 (CentOS)";s:12:"x-powered-by";s:9:"PHP/4.3.9";s:10:"set-cookie";s:136:"SESS2754815166bb8308da6bda14870681d4=08eae1dfd951506f09503b413f0e403e; expires=Mon, 04-Feb-2008 18:18:23 GMT; path=/; domain=.povnet.org";s:7:"expires";s:29:"Sun, 19 Nov 1978 05:00:00 GMT";s:13:"last-modified";s:29:"Sat, 12 Jan 2008 14:45:03 GMT";s:13:"cache-control";s:59:"store, no-cache, must-revalidate, post-check=0, pre-check=0";s:10:"connection";s:5:"close";s:17:"transfer-encoding";s:7:"chunked";s:12:"content-type";s:23:"text/xml; charset=utf-8";}s:5:"build";d:20080102221556;}